version: '3'

services:
    app:
        container_name: crypto-pro
        image: crypto-pro:latest
        command: uvicorn main:app --reload --port 8000 --host 0.0.0.0
        volumes:
          - "./app/:/app"
        ports:
          - 8002:8000